name: Actualizar Precio Binance

on:
  schedule:
    # Se ejecuta cada 12 horas (00:00 y 12:00 UTC)
    - cron: '0 */12 * * *'
  workflow_dispatch: # Permite ejecutarlo manualmente desde la pestaña Actions

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permiso para que el robot pueda guardar el data.json

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar librerias
        run: pip install requests pytz

      - name: Ejecutar Scraper
        run: python scraper.py

      - name: Guardar cambios en GitHub
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add data.json
          git commit -m "Actualización automática de precio: $(date)" || exit 0
          git push
          
