name: Actualizar Precio Binance

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    
    # Aquí forzamos el uso de Node 24 para eliminar la advertencia
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4 # Actualizado a v4

      - name: Configurar Python
        uses: actions/setup-python@v5 # Actualizado a v5
        with:
          python-version: '3.11'

      - name: Instalar librerias
        run: pip install requests pytz

      - name: Ejecutar Scraper
        run: python scraper.py

      - name: Guardar cambios en GitHub
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add data.json
          git commit -m "Actualización automática de precio: $(date)" || exit 0
          git push
          
